#!/bin/bash
# For GCC configurations please look at crosstool-ng-config

# The vendor part has to be changed also in the crosstool-ng-config file
TUPLE=$MACHINE-osquery-linux-gnu

ZLIB_VER="1.2.12"
ZLIB_URL="https://zlib.net/zlib-${ZLIB_VER}.tar.gz"
ZLIB_SHA="91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9"

LLVM_VERSION="12.0.1"
GCC_VERSION="8.3.0" # Notice: this has to match the same version that has been configured in crosstool-ng-config

PARALLEL_JOBS=$(( $(nproc)+1 ))
BUILD_GENERATOR="Ninja"

# Valid values: Release, RelWithDebInfo, MinSizeRel, Debug
LLVM_BUILD_TYPE=MinSizeRel

# If this is false, only the last stage with the clang compile and the first stage, with crosstool gcc will be kept
KEEP_INTERMEDIATE_STAGES=1
